### PR TITLE
ueber jar support - detection of current placeholder - fixes performance problems

### PR DESCRIPTION
**Pull request by MarcGiffing**
As a precaution it should be tested in an application container. Only tested with Spring Boot and embedded Tomcat.

### CODE REVIEW

**Comment by MarcGiffing** [comment]
Ah sorry. The removal of the guava dependency is also in the pull request...

It seems that the wicket7 branch uses Java 1.7 but Travis is configured to use 1.6. Did I have to add a pull request to the master branch?

**Comment by martin-g** [comment]
Thanks a lot for this contribution!
I've tested the Wicket 7 and everything was fine both in embedded Jetty and standalone Tomcat.

I'll have to test master branch before making the release because there were some problems with the cherry-picking!

**Comment by martin-g** [comment]
@MarcGiffing Enjoy your `@web.de` (based on Wicket) account! :-)
I've worked with @l0rdn1kk0n on it!

**Comment by MarcGiffing** [comment]
Thank you! :+1: 
I enjoy web.de almost every day! Thanks you both for that! :-)

**Pull request merged**
