### PR TITLE
module-info is added; M2 structure is applied

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Review by martin-g — APPROVED** [review]

**Comment by solomax** [comment]
@martin-g could you please release this one? :)

**Comment by martin-g** [comment]
Hm, the build locally fails with:
```
$ mvn17 clean install
...
[INFO] 
[INFO] 
[INFO] --- source:3.3.0:jar (default) @ wicket-webjars ---
[ERROR] We have duplicated artifacts attached.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for wicket-webjars-parent 4.0.1-SNAPSHOT:
[INFO] 
[INFO] wicket-webjars-parent .............................. SUCCESS [  1.981 s]
[INFO] library ............................................ FAILURE [  3.381 s]
[INFO] samples ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.547 s
[INFO] Finished at: 2023-10-19T11:46:16+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-source-plugin:3.3.0:jar (default) on project wicket-webjars: Presumably you have configured maven-source-plugn to execute twice times in your build. You have to configure a classifier for at least on of them. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :wicket-webjars
```

**Comment by martin-g** [comment]
Same for `jar-no-fork`:
```
...
 source:3.3.0:jar-no-fork (default) @ wicket-webjars ---
[ERROR] We have duplicated artifacts attached.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for wicket-webjars-parent 4.0.1-SNAPSHOT:
[INFO] 
[INFO] wicket-webjars-parent .............................. SUCCESS [  1.776 s]
[INFO] library ............................................ FAILURE [  2.959 s]
[INFO] samples ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.916 s
[INFO] Finished at: 2023-10-19T11:50:43+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-source-plugin:3.3.0:jar-no-fork (default) on project wicket-webjars: Presumably you have configured maven-source-plugn to execute twice times in your build. You have to configure a classifier for at least on of them. -> [Help 1]
[ERROR] 
```

**Comment by martin-g** [comment]
Fixed with 20e1435

**Comment by martin-g** [comment]
> @martin-g could you please release this one? :)

Done!

**Comment by solomax** [comment]
green for me :(

Thanks for the release! :)

**Pull request merged**
