### PR TITLE
Fixes #32 - Removed hard-coded depth limit for webjars hierarchy

### LINKED ISSUE #32: Unable to use webjars with deep hierarchy (more than 5 levels)
We have a webjar structure deeper than 5 (currently hard-coded value for FileAssetPathCollector#MAX_DIRECTORY_DEPTH), and our Wicket application is unable to start when loading webjar content from file system. Why is this max depth value set at all, and it should at least be configurable.

### PR DESCRIPTION
**Pull request by erikgb**

### CODE REVIEW

**Comment by martin-g** [comment]
Looks safe to me!
Thanks!

**Comment by erikgb** [comment]
Thanks for merging my changes @martin-g! Do you know when this will be availiable in a released version? Do you have any plans for a patch release soon?

**Comment by martin-g** [comment]
0.4.6 is on its way to Maven central!
Have fun!

**Comment by erikgb** [comment]
Excellent! Thanks a lot!

**Pull request merged**
